const errors = {
  'AUTH': {
    'TOKEN_ABSENT': '00000-TOKENS_ABSENT',
    'ACCESS_TOKEN_EXPIRED': '00001-ACCESS_TOKEN_EXPIRED',
    'REFRESH_TOKEN_EXPIRED': '00002-REFRESH_TOKEN_EXPIRED'
  },
  'UNKNOW': '99999-UNKNOW'
}

export { errors }
